import { AlertCircle, ArrowRight, CircleHelp, FileSearch, Layers3, ShieldAlert } from 'lucide-react'
import type { ApplicationModelReadModel, ApplicationModelSubject } from './applicationModelTypes'

const stateLabel: Record<ApplicationModelReadModel['applicationModel']['state'], string> = {
  current: 'Current', stale: 'Stale', unavailable: 'Unavailable', blocked: 'Blocked', incomplete: 'Incomplete', 'integrity-limited': 'Integrity limited',
}

function SubjectCard({ subject }: { subject: ApplicationModelSubject }) {
  const derived = subject.basis === 'derived-interpretation'
  return (
    <article className="rounded border border-border bg-elevated p-4" data-model-subject={subject.id}>
      <div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs uppercase tracking-wide text-muted">{subject.kind}</p><h3 className="mt-1 text-sm font-semibold text-primary">{subject.label}</h3></div><span className={`rounded border border-border px-2 py-1 text-[11px] ${derived ? 'text-flaky' : 'text-pass'}`}>{derived ? 'Derived interpretation' : 'Direct observation'}</span></div>
      <p className="mt-3 text-sm text-secondary">{subject.summary}</p>
      {derived && subject.interpretation && <p className="mt-3 border-l-2 border-flaky pl-3 text-xs text-flaky">Interpretation: {subject.interpretation}</p>}
      <div className="mt-3 space-y-1 text-xs text-muted"><p>Observation: {subject.observationIds.length > 0 ? subject.observationIds.join(', ') : 'none supplied'}</p><p>Evidence: {subject.evidenceIds.length > 0 ? subject.evidenceIds.join(', ') : 'none supplied'}</p><p>Context: {subject.observationContextIds.length > 0 ? subject.observationContextIds.join(', ') : 'none supplied'}</p></div>
    </article>
  )
}

export function ApplicationModel({ readModel }: { readModel: ApplicationModelReadModel }) {
  const model = readModel.applicationModel
  const stateColor = model.state === 'current' ? 'text-pass' : model.state === 'stale' || model.state === 'incomplete' ? 'text-flaky' : 'text-unknown'
  return (
    <div className="space-y-6" data-testid="application-model">
      <header><p className="text-xs uppercase tracking-[0.18em] text-brand">Application Model</p><h1 className="mt-1 text-2xl font-semibold text-primary">What FORGE currently understands</h1><p className="mt-1 text-sm text-secondary">A model of observed application structure—not the application itself.</p></header>
      <section className="rounded-lg border border-border bg-surface p-5" aria-labelledby="model-state"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-muted">Model state</p><h2 id="model-state" className={`mt-1 text-xl font-semibold ${stateColor}`}>{stateLabel[model.state]}</h2></div><Layers3 size={20} className="text-brand" /></div><p className="mt-3 text-sm text-secondary">{model.why}</p><dl className="mt-4 grid grid-cols-1 gap-3 text-xs sm:grid-cols-2 lg:grid-cols-5"><div><dt className="text-muted">Revision / identity</dt><dd className="mt-1 text-secondary">{model.revision ?? 'Not available'}</dd></div><div><dt className="text-muted">Generated</dt><dd className="mt-1 text-secondary">{model.generatedAt ?? 'Not available'}</dd></div><div><dt className="text-muted">Evaluated</dt><dd className="mt-1 text-secondary">{model.evaluatedAt ?? 'Not available'}</dd></div><div><dt className="text-muted">Source observations</dt><dd className="mt-1 text-secondary">{model.sourceObservationIds.length > 0 ? model.sourceObservationIds.join(', ') : 'None supplied'}</dd></div><div><dt className="text-muted">Currency support</dt><dd className="mt-1 text-secondary">{model.currencyEvidenceIds.length > 0 ? model.currencyEvidenceIds.join(', ') : 'None supplied'}</dd></div></dl>{model.preventedStrongerState && <p className="mt-4 border-l-2 border-unknown pl-3 text-xs text-unknown">Prevents a stronger state: {model.preventedStrongerState}</p>}<p className="mt-4 text-sm text-secondary">Impact: {model.impact}</p></section>

      <section aria-labelledby="understood-structure"><div className="mb-3 flex items-center gap-2"><Layers3 size={16} className="text-brand" /><h2 id="understood-structure" className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary">Observed structure</h2></div>{readModel.modelSubjects.length === 0 ? <div className="rounded-lg border border-border bg-surface p-8 text-center"><p className="text-sm text-secondary">No modeled subjects are available from the supplied observations.</p><p className="mt-1 text-xs text-muted">No item count is used as a completeness claim.</p></div> : <div className="grid grid-cols-1 gap-4 lg:grid-cols-2">{readModel.modelSubjects.map(subject => <SubjectCard key={subject.id} subject={subject} />)}</div>}</section>

      <section className="rounded-lg border border-border bg-surface p-5" aria-labelledby="model-provenance"><div className="flex items-center gap-2"><FileSearch size={16} className="text-brand" /><div><p className="text-xs uppercase tracking-[0.16em] text-muted">Provenance and currency</p><h2 id="model-provenance" className="mt-1 text-xl font-semibold text-primary">How this model was formed</h2></div></div><p className="mt-3 text-sm text-secondary">Direct observations and derived interpretations are labeled separately on each subject. Source observation and evidence references are shown as supplied; incompatible contexts are not silently merged.</p><div className="mt-4 grid grid-cols-1 gap-4 md:grid-cols-2"><div className="rounded border border-border bg-elevated p-4"><p className="text-xs uppercase tracking-wide text-muted">Currency evidence</p><p className="mt-2 font-mono text-xs text-secondary">{model.currencyEvidenceIds.length > 0 ? model.currencyEvidenceIds.join(', ') : 'No currency evidence supplied'}</p></div><div className="rounded border border-border bg-elevated p-4"><p className="text-xs uppercase tracking-wide text-muted">Source observations</p><p className="mt-2 font-mono text-xs text-secondary">{model.sourceObservationIds.length > 0 ? model.sourceObservationIds.join(', ') : 'No source observations supplied'}</p></div></div></section>

      <section className="rounded-lg border border-border bg-surface p-5" aria-labelledby="model-limitations"><p className="text-xs uppercase tracking-[0.16em] text-muted">Coverage limitations</p><h2 id="model-limitations" className="mt-1 text-xl font-semibold text-primary">What the model does not establish</h2>{readModel.modelUnobservedScope.length > 0 && <div className="mt-3"><p className="text-xs uppercase tracking-wide text-muted">Unobserved scope</p><ul className="mt-2 space-y-1 text-sm text-secondary">{readModel.modelUnobservedScope.map(item => <li key={item}>· {item}</li>)}</ul></div>}{readModel.modelLimitations.length > 0 && <div className="mt-3"><p className="text-xs uppercase tracking-wide text-muted">Limitations</p><ul className="mt-2 space-y-1 text-sm text-secondary">{readModel.modelLimitations.map(item => <li key={item}>· {item}</li>)}</ul></div>}{readModel.modelUnobservedScope.length === 0 && readModel.modelLimitations.length === 0 && <p className="mt-3 text-sm text-muted">No additional limitations supplied; this is not a completeness claim.</p>}</section>

      {(readModel.modelUnknowns.length > 0 || readModel.modelBlockers.length > 0) && <section className="grid grid-cols-1 gap-4 md:grid-cols-2" aria-label="Model unknowns and blockers">{readModel.modelBlockers.length > 0 && <div className="rounded-lg border border-fail/40 bg-elevated p-4"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-fail"><ShieldAlert size={14} /> Blockers</p><ul className="mt-2 space-y-1 text-sm text-secondary">{readModel.modelBlockers.map(item => <li key={item}>{item}</li>)}</ul></div>}{readModel.modelUnknowns.length > 0 && <div className="rounded-lg border border-unknown/40 bg-elevated p-4"><p className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-unknown"><CircleHelp size={14} /> Unknowns</p><ul className="mt-2 space-y-1 text-sm text-secondary">{readModel.modelUnknowns.map(item => <li key={item}>{item}</li>)}</ul></div>}</section>}

      {model.state === 'unavailable' && <p className="flex gap-2 rounded border border-unknown/40 bg-elevated p-4 text-sm text-secondary"><AlertCircle size={16} className="mt-0.5 shrink-0 text-unknown" />No Application Model is available. No structure is inferred.</p>}
      {readModel.modelRecommendation ? <div className="flex gap-2 rounded border border-border bg-surface p-4 text-sm text-secondary"><ArrowRight size={16} className="mt-0.5 shrink-0 text-brand" /><span><strong className="text-primary">Next: {readModel.modelRecommendation.action}</strong><span className="mt-1 block text-xs text-muted">Because: {readModel.modelRecommendation.because}</span></span></div> : <p className="flex gap-2 rounded border border-border bg-surface p-4 text-sm text-muted"><AlertCircle size={16} className="mt-0.5 shrink-0 text-unknown" />No safe recommendation is available for the current model evidence.</p>}
    </div>
  )
}
