import { AlertCircle, CircleHelp, FileSearch, Filter, Link2, ShieldAlert } from 'lucide-react'
import { useMemo, useState } from 'react'
import type { EvidenceLedgerRecord, ApplicationEvidenceReadModel } from './evidenceTypes'

type LedgerFilter = 'all' | 'current' | 'historical'
const freshnessLabel: Record<EvidenceLedgerRecord['freshness'], string> = { current: 'Current', stale: 'Stale', expired: 'Expired', unavailable: 'Unavailable', superseded: 'Superseded' }
const integrityLabel: Record<EvidenceLedgerRecord['integrity'], string> = { verified: 'Verified', failed: 'Failed', unknown: 'Unknown', limited: 'Limited' }

function EvidenceRecord({ evidence }: { evidence: EvidenceLedgerRecord }) {
  const freshnessColor = evidence.freshness === 'current' ? 'text-pass' : 'text-flaky'
  const integrityColor = evidence.integrity === 'verified' ? 'text-pass' : evidence.integrity === 'failed' ? 'text-fail' : 'text-unknown'
  return (
    <article className="rounded-lg border border-border bg-surface p-5" data-evidence-id={evidence.id}>
      <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.16em] text-muted">{evidence.sourceKind}</p><h3 className="mt-1 font-mono text-sm font-semibold text-primary">{evidence.id}</h3></div><div className="flex gap-2 text-xs"><span className={`rounded-full border border-border px-2 py-1 ${freshnessColor}`}>{freshnessLabel[evidence.freshness]}</span><span className={`rounded-full border border-border px-2 py-1 ${integrityColor}`}>{integrityLabel[evidence.integrity]}</span></div></div>
      <dl className="mt-4 grid grid-cols-1 gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt className="text-xs uppercase tracking-wide text-muted">Subject</dt><dd className="mt-1 text-secondary">{evidence.subject}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted">Project</dt><dd className="mt-1 font-mono text-xs text-secondary">{evidence.projectId}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted">Observation context</dt><dd className="mt-1 text-secondary">{evidence.observationContextLabel}{evidence.observationContextId ? ` (${evidence.observationContextId})` : ''}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted">Support</dt><dd className="mt-1 text-secondary">{evidence.support}</dd></div></dl>
      <p className="mt-4 text-sm text-secondary">{evidence.observationSummary}</p>
      <div className="mt-4 grid grid-cols-1 gap-3 text-xs md:grid-cols-2"><div className="rounded border border-border bg-elevated p-3"><p className="text-muted">Captured / observed</p><p className="mt-1 text-secondary">{evidence.capturedAt ?? 'Captured time unavailable'} · {evidence.observedAt ?? 'Observed time unavailable'}</p><p className="mt-2 text-muted">Freshness: {evidence.freshnessExplanation}</p></div><div className="rounded border border-border bg-elevated p-3"><p className="text-muted">Integrity</p><p className="mt-1 text-secondary">{evidence.integrityExplanation}</p>{evidence.credentialMaterialOmitted && <p className="mt-2 text-unknown">Credential material omitted from presentation.</p>}</div></div>
      {evidence.sourceReference ? <p className="mt-3 text-xs text-muted">Source / run: <span className="font-mono text-secondary">{evidence.sourceReference}</span></p> : <p className="mt-3 text-xs text-unknown">Source / run provenance is missing.</p>}
      {evidence.accessLimitation && <p className="mt-3 flex gap-2 rounded border border-flaky/40 bg-elevated p-3 text-xs text-flaky"><AlertCircle size={14} className="mt-0.5 shrink-0" />{evidence.accessLimitation}</p>}
      <div className="mt-4 border-t border-border pt-3 text-xs"><p className="flex items-center gap-2 uppercase tracking-wide text-muted"><Link2 size={13} /> Used by</p><p className="mt-1 text-secondary">Truth Cards: {evidence.truthCardReferences.length > 0 ? evidence.truthCardReferences.join(', ') : 'none supplied'} · Model: {evidence.modelReferences.length > 0 ? evidence.modelReferences.join(', ') : 'none supplied'}</p><p className="mt-1 text-secondary">Claims / recommendations: {evidence.claimReferences.length > 0 ? evidence.claimReferences.join(', ') : 'none supplied'}</p></div>
      {evidence.conflictingGroupId && <p className="mt-3 flex gap-2 text-xs text-fail"><ShieldAlert size={14} className="mt-0.5 shrink-0" />Unresolved conflict group: {evidence.conflictingGroupId}</p>}
    </article>
  )
}

export function ApplicationEvidence({ readModel }: { readModel: ApplicationEvidenceReadModel }) {
  const [filter, setFilter] = useState<LedgerFilter>('all')
  const visibleEvidence = useMemo(() => readModel.evidenceLedger.filter(item => filter === 'all' || (filter === 'current' ? item.freshness === 'current' : item.freshness !== 'current')), [filter, readModel.evidenceLedger])
  return (
    <div className="space-y-6" data-testid="application-evidence">
      <header><p className="text-xs uppercase tracking-[0.18em] text-brand">Evidence</p><h1 className="mt-1 text-2xl font-semibold text-primary">What supports FORGE's understanding</h1><p className="mt-1 text-sm text-secondary">A readable evidence ledger for {readModel.project.displayName}. Evidence existence is not evidence sufficiency.</p></header>
      <section className="rounded-lg border border-border bg-surface p-5" aria-labelledby="evidence-ledger"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><FileSearch size={17} className="text-brand" /><h2 id="evidence-ledger" className="text-xl font-semibold text-primary">Evidence ledger</h2></div><label className="flex items-center gap-2 text-xs text-secondary"><Filter size={14} /><span className="sr-only">Filter evidence</span><select value={filter} onChange={event => setFilter(event.target.value as LedgerFilter)} className="rounded border border-border bg-elevated px-2 py-1 text-secondary"><option value="all">All evidence</option><option value="current">Current only</option><option value="historical">Historical / limited</option></select></label></div>{readModel.evidenceLedger.length === 0 ? <div className="py-8 text-center"><CircleHelp size={22} className="mx-auto text-unknown" /><p className="mt-3 text-sm text-secondary">No evidence is available for this application.</p><p className="mt-1 text-xs text-muted">No current understanding or completeness claim is inferred.</p></div> : visibleEvidence.length === 0 ? <p className="py-8 text-center text-sm text-muted">No evidence matches this filter.</p> : <div className="mt-4 space-y-4">{visibleEvidence.map(evidence => <EvidenceRecord key={evidence.id} evidence={evidence} />)}</div>}</section>
      {readModel.evidenceConflicts.length > 0 && <section aria-labelledby="evidence-conflicts"><div className="mb-3 flex items-center gap-2"><ShieldAlert size={16} className="text-fail" /><h2 id="evidence-conflicts" className="text-sm font-semibold uppercase tracking-[0.16em] text-secondary">Unresolved conflicts</h2></div><div className="space-y-3">{readModel.evidenceConflicts.map(conflict => <article key={conflict.id} className="rounded-lg border border-fail/40 bg-elevated p-4"><h3 className="text-sm font-semibold text-primary">{conflict.subject} · {conflict.id}</h3><p className="mt-2 text-sm text-secondary">{conflict.unresolvedExplanation}</p><p className="mt-2 text-xs text-muted">Evidence: {conflict.evidenceIds.join(', ')} · Sources: {conflict.sourceReferences.join(', ') || 'not supplied'} · Contexts: {conflict.observationContextIds.join(', ') || 'not supplied'}</p></article>)}</div></section>}
      <section className="rounded-lg border border-border bg-surface p-5" aria-labelledby="evidence-boundary"><p className="text-xs uppercase tracking-[0.16em] text-muted">Context boundaries and impact</p><h2 id="evidence-boundary" className="mt-1 text-xl font-semibold text-primary">How evidence may be used</h2><p className="mt-3 text-sm text-secondary">Each record retains its project and observation context. Current support, historical-only status, claim references, model references, stale evidence, and integrity limitations are supplied by the read model and shown above. Evidence from incompatible contexts is not merged here.</p><p className="mt-3 text-xs text-muted">Credential material, tokens, cookies, and secrets are not display fields in this presentation.</p></section>
    </div>
  )
}
